run-tp5:
	cd tp5-parseur_fichier && cargo run

run-tp6:
	cd tp6-abstration_generique && cargo run

build-all:
	for d in tp*; do (cd $$d && cargo build); done

clean-all:
	for d in tp*; do (cd $$d && cargo clean); done